DATASET:
  root_dir: "data/face_dataset"
  class_labels: ["3/4_left_sideview",
    "3/4_rigth_sideview",
    "Frontal",
    "Left_sideview",
    "Right_sideview"]

DATALOADER:
  num_workers: 4
  train_dataset: train
  val_dataset: val
  num_gpus: 2

MODEL:
  base_config_path: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  rotated_bbox_config_path: "rotated_bbox_config.yaml"
  pretrained_model_url: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  num_classes: 5
  device: "cuda"
  freeze_backbone: False
  freeze_at_block: 3
  output_dir: "./output"

TRAINING:
  ims_per_batch: 4
  checkpoint_period: 1000
  base_lr: 0.0025 
  epochs:  100
  batch_size_per_image: 128
  warm_steps: 1000
  gamma: 0.1

