path: /Users/jocareher/Downloads/obb_testing/
train: train/images
val: val/images
test: test/images

nc: 5
names: ["3/4_left_sideview", "3/4_rigth_sideview", "Frontal", "Left_sideview", "Right_sideview"]